### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by nicerok11** [iZwnMswn/kernel_xiaomi_msm8992-lineage-15.1#1]
I'm trying to compile Lineage 15.1 with your kernel from "hatekernel-new" branch and getting this

/root/android/lineage/kernel/xiaomi/msm8992/scripts/Makefile.build:308: recipe for target 'net/ipv4/devinet.o' failed
make[3]: *** [net/ipv4/devinet.o] Error 1
/root/android/lineage/kernel/xiaomi/msm8992/scripts/Makefile.build:455: recipe for target 'net/ipv4' failed
make[2]: *** [net/ipv4] Error 2
/root/android/lineage/kernel/xiaomi/msm8992/Makefile:824: recipe for target 'net' failed
make[1]: *** [net] Error 2
Makefile:130: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2
make: Leaving directory '/root/android/lineage/kernel/xiaomi/msm8992'
[ 19% 18621/96492] //external/libcxx:libc++_static clang++ src/algorithm.cpp [arm]
ninja: build stopped: subcommand failed.
07:07:37 ninja failed with: exit status 1

**Comment by iZwnMswn** [comment]
Which defconfig did you use? Try libra_defconfig.

**Comment by zah0** [comment]
i try libra_defconfig, in miui10 was bootloop
and i found that  make[1]: *** No rule to make target 'arch/arm64/boot/dts/x11-msm8992 .dtb'
your makefile lack sth, I fix it ,get image-dtb,  but when i use anykernel flash it to my phone , bootloop....

**Comment by zah0** [comment]
new error with libra_defconfig，when i make modules appeared   `MODPOST 0 modules`

branch: kernel_xiaomi_msm8992-lineage-15.1-HateKernel_libra-Oreo
GCC:aarch64-4.9


```
HOSTCC  scripts/mod/file2alias.o
<stdin>:1226:2: warning: #warning syscall sched_setattr not implemented [-Wcpp]
<stdin>:1229:2: warning: #warning syscall sched_getattr not implemented [-Wcpp]
  HOSTLD  scripts/mod/modpost
  CHK     include/generated/compile.h
  GZIP    kernel/config_data.gz
  CHK     kernel/config_data.h
make[1]: Nothing to be done for 'dtbs'.
make[1]: Nothing to be done for 'dtbs'.
make[1]: 'arch/arm64/boot/Image-dtb' is up to date.
  Building modules, stage 2.
  MODPOST 0 modules

```

**Comment by zah0** [comment]
sorry it maybe missing folder links when i download zip

**Comment by iZwnMswn** [comment]
Usually that was that missing .dtb was caused by missing symlink to its
reference. My way of fixing it was by simply ln -s into the /boot folder in
arm64 target.

Other than that, try passing -no-Werror argument in compiler. I'll check
later for my exact config as I'm currently away from home.
